package ModulesElements.Merchants;

import org.openqa.selenium.By;

public class Merchant {

    public static final By userIdFiled = By.cssSelector(".InputTableRow > td:nth-child(2) > input:nth-child(1)");
    public static final By passwordField = By.cssSelector(".loginTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > input:nth-child(1)");
    public static final By signIn = By.cssSelector("#login");
    public static final By merchantsField = By.xpath("//*[@id=\"wrapper\"]/ul/li[4]/a");
    public static final By createMerchantField = By.xpath("/html/body/div[4]/navp/div[3]/div/ul/li[4]/ul/li[3]/a");
    public static final By merchantTypeDropbox = By.xpath("//*[@id=\"merchantType\"]");
    public static final By merchantTypeMerchantField = By.xpath("//*[@translate=\"merchant_type_merchant\"][1]");
    public static final By fullnameField = By.xpath("//*[@id=\"fullName\"]");
    public static final By shortNameField = By.xpath("//*[@id=\"shortName\"]");
    public static final By tradeNameOrganizationField = By.xpath("//*[@placeholder=\"Trade Name of the Organization\"]");
    public static final By organizationFormField = By.xpath("//*[@placeholder=\"Organization form\"]");
    public static final By businessEntityDropbox = By.xpath("//*[@name=\"businessEntityType\"]");
    public static final By businessEntityTypePrivateField = By.xpath("//*[@name=\"businessEntityType\"]/option[2]");
    public static final By businessEntityTypeLegalField = By.xpath("//*[@name=\"businessEntityType\"]/option[1]");
    public static final By listOfMerchantsPointsOfSaleCreateNewPointOfSaleButton = By.xpath("//*[@translate=\"general_button_create_new_pos\"]");
    public static final By newPosNameField = By.xpath("//*[@id=\"newPosName\"]");
    public static final By newPosAddressField = By.xpath("//*[@id=\"newPosAddress\"]");
    public static final By addPosButton = By.xpath("//*[@ng-click=\"newPosAdd()\"]");
    public static final By listOfregionswhereMerchantOperatesDropdown = By.xpath("//*[@ng-click=\"toggleDropdown()\"]");
    public static final By listOfRegionsVinnytskaobl = By.xpath("//*[contains(text(),'Вінницька обл.')]");
    public static final By legalAddressFiled = By.xpath("//*[@ng-model = \"merchant.legalAddress\"]");
    public static final By actualAddressFiled = By.xpath("//*[@ng-model = \"merchant.actualAddress\"]");
    public static final By correspondenceAddressFiled = By.xpath("//*[@ng-model = \"merchant.correspondenceAddress\"]");
    public static final By phoneNumberField = By.xpath("//*[@ng-model = \"merchant.contactPhoneNumber\"]");
    public static final By contactEmailField = By.xpath("//*[@ng-model = \"merchant.contactEmail\"]");
    public static final By contactWebsiteField = By.xpath("//*[@ng-model = \"merchant.contactWebsite\"]");
    public static final By contactCallCenterNumberField = By.xpath("//*[@name = 'callCenterNumber']");
    public static final By notificationChannelSmsField = By.xpath("//*[@name = \"merchant_receive_sms\"]");
    public static final By notificationChannelEmailField = By.xpath("//*[@name = \"merchant_receive_email\"]");
    public static final By nextButtonCompany = By.xpath("//*[@id=\"companyDetailsFormNext\"]");
    public static final By IDOfMerchantContractWithAgentForSettlement0Field = By.xpath("//*[@id=\"agreementContractId0\"]");
    public static final By dateofMerchantContractWithAgentDate0Picker = By.xpath(" //*[@name=\"contractDate0\"]");
    public static final By agreementContractScan0Button = By.xpath("//*[@id=\"agreementContractScan0\"]");
    public static final By IDOfMerchantContractWithAgentForSettlement1Field = By.xpath("//*[@id=\"agreementContractId1\"]");
    public static final By dateofMerchantContractWithAgentDate1Picker = By.xpath(" //*[@id=\"contractDate1\"]");
    public static final By agreementContractScan1Button = By.xpath("//*[@id=\"agreementContractScan1\"]");
    public static final By IDOfMerchantContractWithAgentForSettlement2Field = By.xpath("//*[@id=\"agreementContractId2\"]");
    public static final By dateofMerchantContractWithAgentDate2Picker = By.xpath(" //*[@id=\"contractDate2\"]");
    public static final By agreementContractScan2Button = By.xpath("//*[@id=\"agreementContractScan2\"]");
    public static final By IDOfMerchantContractWithAgentForSettlement3Field = By.xpath("//*[@id=\"agreementContractId3\"]");
    public static final By dateofMerchantContractWithAgentDate3Picker = By.xpath(" //*[@id=\"contractDate3\"]");
    public static final By agreementContractScan3Button = By.xpath("//*[@id=\"agreementContractScan3\"]");
    public static final By scanCopyOfStatueButton = By.xpath("//*[@id=\"agreementOtherDocumentStatuteScan\"]");
    public static final By scanCopyOfTaxIdButton = By.xpath("//*[@id=\"agreementOtherDocumentTaxCertificateScan\"]");
    public static final By scanStatementOfCsrButton = By.xpath("//*[@id=\"agreementOtherDocumentStatementFromCsrScan\"]");
    public static final By scanStatementExtractFromCsrButton = By.xpath("//*[@id=\"agreementOtherDocumentExtractFromCsrScan\"]");
    public static final By scanStatementQuestionnareButton = By.xpath("//*[@id=\"agreementOtherDocumentQuestionnaireScan\"]");
    public static final By fullNameContactField = By.xpath(" //*[@id=\"fullNamemerchant_representative_data_director\"]");
    public static final By positionContactField = By.xpath(" //*[@id=\"positionmerchant_representative_data_director\"]");
    public static final By countryOfResidence = By.xpath("//*[@id=\"countryOfResidencemerchant_representative_data_director\"]");
    public static final By mobileNumberContactField = By.xpath(" //*[@id=\"mobileNumbermerchant_representative_data_director\"]");
    public static final By workEmailContactField = By.xpath(" //*[@id=\"workEmailmerchant_representative_data_director\"]");
    public static final By accountFullNameContactField = By.xpath(" //*[@id=\"fullNamemerchant_representative_data_chief_accountant\"]");
    public static final By accountPositionContactField = By.xpath(" //*[@id=\"positionmerchant_representative_data_chief_accountant\"]");
    public static final By accountCountryOfResidence = By.xpath("//*[@id=\"countryOfResidencemerchant_representative_data_chief_accountant\"]");
    public static final By accountMobileNumberContactField = By.xpath(" //*[@id=\"mobileNumbermerchant_representative_data_chief_accountant\"]");
    public static final By accountWorkEmailContactField = By.xpath(" //*[@id=\"workEmailmerchant_representative_data_chief_accountant\"]");
    public static final By operationFullNameContactField = By.xpath(" //*[@id=\"fullNamemerchant_representative_data_contact_operational_issues\"]");
    public static final By operationPositionContactField = By.xpath(" //*[@id=\"positionmerchant_representative_data_contact_operational_issues\"]");
    public static final By operationMobileNumberContactField = By.xpath(" //*[@id=\"mobileNumbermerchant_representative_data_contact_operational_issues\"]");
    public static final By operationWorkEmailContactField = By.xpath(" //*[@id=\"workEmailmerchant_representative_data_contact_operational_issues\"]");
    public static final By fullNameContactITField = By.xpath(" //*[@id=\"fullNamemerchant_representative_data_contact_it_issues\"]");
    public static final By positionContactITField = By.xpath(" //*[@id=\"positionmerchant_representative_data_contact_it_issues\"]");
    public static final By mobileNumberContactITField = By.xpath(" //*[@id=\"mobileNumbermerchant_representative_data_contact_it_issues\"]");
    public static final By workEmailContactITField = By.xpath(" //*[@id=\"workEmailmerchant_representative_data_contact_it_issues\"]");
    public static final By fullNameContactFinField = By.xpath(" //*[@id=\"fullNamemerchant_representative_data_contact_financial_issues\"]");
    public static final By positionContactFinField = By.xpath(" //*[@id=\"positionmerchant_representative_data_contact_financial_issues\"]");
    public static final By mobileNumberContactFinField = By.xpath(" //*[@id=\"mobileNumbermerchant_representative_data_contact_financial_issues\"]");
    public static final By workEmailContactFinField = By.xpath(" //*[@id=\"workEmailmerchant_representative_data_contact_financial_issues\"]");
    public static final By accountNoCompanyDetailsField = By.xpath("//*[@id=\"merchant_representative_company_details_account_no\"]");
    public static final By bankNameCompanyDetailsField = By.xpath("//*[@id=\"merchant_representative_company_details_bank_name\"]");
    public static final By bankIdComapnyDetailsField = By.xpath("//*[@id=\"merchant_representative_company_details_bank_id\"]");
    public static final By stateEnterpriseRegistryIdField = By.xpath("//*[@id=\"merchant_representative_company_details_state_enterprise_registry_id\"]");
    public static final By contractSigneeNameField = By.xpath("//*[@id=\"merchant_representative_company_details_contract_signee_name\"]");
    public static final By contractSigneePositionField = By.xpath("//*[@id=\"merchant_representative_company_details_contract_signee_position\"]");
    public static final By contractSigneeBasisField = By.xpath("//*[@id=\"merchant_representative_company_details_contract_signee_basis\"]");
    public static final By contractSigneeFullnameField = By.xpath("//*[@id=\"merchant_representative_company_details_contract_signee_tab_full_name\"]");
    public static final By contractSigneePositionField1 = By.xpath(" //*[@id=\"merchant_representative_company_details_contract_signee_tab_postion\"]");
    public static final By contractSigneeMobileNumberField = By.xpath(" //*[@id=\"merchant_representative_company_details_contract_signee_tab_mobile\"]");
    public static final By signeePassportScanButton = By.xpath(" //*[@id=\"signeePassportScan\"]");
    public static final By signeeTaxIdScanButton = By.xpath(" //*[@id=\"signeeTaxIdScan\"]");
    public static final By signeeAuthorizingScanButton = By.xpath(" //*[@id=\"signeeAuthorScan\"]");
    public static final By NextButton = By.xpath("//*[@id=\"regRepDetailNext\"]");
    public static final By NextButton2 = By.xpath("//*[@id=\"representativeDataForm\"]//button[@name='regRepDetailNext']");
    public static final By NextButton3 = By.xpath("//*[@id=\"content\"]/div[4]/div/div/section[4]/form//p//button[@translate='general_button_next']");
    public static final By numberOfWorkingDaysForFundsInbankField = By.xpath("//*[@placeholder=\"Number of working days for funds will be available in bank after fund-out\"]");
    public static final By merchantApiField = By.xpath("//*[@id=\"apiUrl\"]");
    public static final By feeForRefundField = By.xpath("//*[@placeholder=\"Fee for refund\"]");
    public static final By turnoverOverLastYearField = By.xpath("//*[@placeholder=\"Turnover over the last business year, UAH\"]");
    public static final By testServerIpField = By.xpath("//*[@placeholder=\"Test server IP\"]");
    public static final By testServerPortField = By.xpath("//*[@placeholder=\"Test server port\"]");
    public static final By testProductionServerIpField = By.xpath("//*[@placeholder=\"Production server IP\"]");
    public static final By testProductionServerPortField = By.xpath("//*[@placeholder=\"Production server port\"]");
    public static final By bankdetailRecipientNameField0 = By.xpath("//*[@id=\"bankDetailRecipientNamebd0\"]");
    public static final By bankdetailRecipientIdField0 = By.xpath("//*[@id=\"bankDetailRecipientIdbd0\"]");
    public static final By bankdetailRecipientAccountNoField0 = By.xpath("//*[@id=\"bankDetailAccountNumberbd0\"]");
    public static final By bankdetailRecipientBankCodeField0 = By.xpath("//*[@id=\"bankDetailBankCodebd0\"]");
    public static final By bankdetailRecipientBankNameField0 = By.xpath("//*[@id=\"bankDetailBankNamebd0\"]");
    public static final By bankdetailRecipientPaymentPurposeField0 = By.xpath("//*[@id=\"bankDetailPaymentPurposebd0\"]");
    public static final By bankdetailRecipientNameField1 = By.xpath("//*[@id=\"bankDetailRecipientNamebd1\"]");
    public static final By bankdetailRecipientIdField1 = By.xpath("//*[@id=\"bankDetailRecipientIdbd1\"]");
    public static final By bankdetailRecipientAccountNoField1 = By.xpath("//*[@id=\"bankDetailAccountNumberbd1\"]");
    public static final By bankdetailRecipientBankCodeField1 = By.xpath("//*[@id=\"bankDetailBankCodebd1\"]");
    public static final By bankdetailRecipientBankNameField1 = By.xpath("//*[@id=\"bankDetailBankNamebd1\"]");
    public static final By bankdetailRecipientPaymentPurposeField1 = By.xpath("//*[@id=\"bankDetailPaymentPurposebd1\"]");
    public static final By bankdetailRecipientNameField2 = By.xpath("//*[@id=\"bankDetailRecipientNamebd2\"]");
    public static final By bankdetailRecipientIdField2 = By.xpath("//*[@id=\"bankDetailRecipientIdbd2\"]");
    public static final By bankdetailRecipientAccountNoField2 = By.xpath("//*[@id=\"bankDetailAccountNumberbd2\"]");
    public static final By bankdetailRecipientBankCodeField2 = By.xpath("//*[@id=\"bankDetailBankCodebd2\"]");
    public static final By bankdetailRecipientBankNameField2 = By.xpath("//*[@id=\"bankDetailBankNamebd2\"]");
    public static final By bankdetailRecipientPaymentPurposeField2 = By.xpath("//*[@id=\"bankDetailPaymentPurposebd2\"]");
    public static final By paymentPurposeField = By.xpath("//*[@id=\"bankDetailPaymentPurposeepr\"]");
    public static final By saveButton = By.xpath("//*[@id=\"regMerchSave\"]");

}
